import "./globals.css"
import Navbar from "./components/Navbar";
import type { Metadata } from "next";
import { Asap } from "next/font/google";

const asap = Asap({ subsets: [
  "latin"
]})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

interface Props {
  children: React.ReactNode;
}


export default function RootLayout({
  children,
}: Props) {
  return (
    <html lang="en">
      <body className={asap.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
